let saludito = document.getElementsByClassName("saludito");
saludito[0].style = "color:blue"
let texto = document.getElementById("container")
texto.innerText = "de què me habla usted";
texto.style = "background-color:orange";
let lista = document.getElementsByTagName("li")
lista[1].innerHTML = "soy el elemento 2";
lista[25].innerHTML = "soy el elemento 26";
lista[25].innerHTML = lista[25].innerHTML + "soy el elemento 26";